<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
  <ItemGroup>
	<InternalsVisibleTo Include="$(Author).$(MSBuildProjectName).UnitTests" />
	<InternalsVisibleTo Include="$(Author).$(MSBuildProjectName).IntegrationTests" />
  </ItemGroup>

<ItemGroup>
  <Content Include="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

<ItemGroup>
  <Content Include="modicon.png" Condition="Exists('modicon.png')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

</Project>
